apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-demo-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/ashmehroz91-cloud/gitops-k3s-demo-manifests-"
    targetRevision: HEAD
    path: "charts/app"
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
